"""Account Move (Invoice/Bill) and Move Line models."""
from datetime import date
from typing import Optional
from sqlalchemy import Boolean, Date, Integer, Numeric, String, ForeignKey
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base, TimestampMixin

class AccountMove(Base, TimestampMixin):
    __tablename__ = "account_move"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    sequence_number: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    journal_id: Mapped[int] = mapped_column(Integer, ForeignKey("account_journal.id"), nullable=False)
    company_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    partner_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    commercial_partner_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    partner_shipping_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    partner_bank_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    fiscal_position_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    currency_id: Mapped[int] = mapped_column(Integer, nullable=False)
    reversed_entry_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    invoice_user_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    invoice_payment_term_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    invoice_cash_rounding_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    invoice_incoterm_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    origin_payment_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    statement_line_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    message_main_attachment_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    secure_sequence_number: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    preferred_payment_method_line_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    tax_cash_basis_rec_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    tax_cash_basis_origin_move_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    auto_post_origin_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    sequence_prefix: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    access_token: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    name: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    ref: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    state: Mapped[str] = mapped_column(String, nullable=False, server_default="draft")
    move_type: Mapped[str] = mapped_column(String, nullable=False)
    auto_post: Mapped[str] = mapped_column(String, nullable=False, server_default="no")
    inalterable_hash: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    payment_reference: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    qr_code_method: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    payment_state: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    invoice_source_email: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    invoice_partner_display_name: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    invoice_origin: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    incoterm_location: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    date: Mapped[date] = mapped_column(Date, nullable=False)
    auto_post_until: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    invoice_date: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    invoice_date_due: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    narration: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    amount_untaxed: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_tax: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_total: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_residual: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_untaxed_signed: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_tax_signed: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_total_signed: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_total_in_currency_signed: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_residual_signed: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    always_tax_exigible: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    is_manually_modified: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    is_move_sent: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    line_ids: Mapped[list["AccountMoveLine"]] = relationship("AccountMoveLine", back_populates="move", lazy="selectin")
    def __repr__(self): return f"<AccountMove(id={self.id}, name={self.name}, state={self.state})>"

class AccountMoveLine(Base, TimestampMixin):
    __tablename__ = "account_move_line"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    move_id: Mapped[int] = mapped_column(Integer, ForeignKey("account_move.id"), nullable=False)
    journal_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    company_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    company_currency_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    sequence: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    account_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    currency_id: Mapped[int] = mapped_column(Integer, nullable=False)
    partner_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    payment_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    full_reconcile_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    product_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    product_uom_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    tax_line_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    tax_group_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    purchase_line_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    cogs_origin_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    reconcile_model_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    statement_line_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    statement_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    group_tax_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    tax_repartition_line_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    move_name: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    parent_state: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    ref: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    name: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    matching_number: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    display_type: Mapped[str] = mapped_column(String, nullable=False)
    date: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    invoice_date: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    date_maturity: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    discount_date: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    analytic_distribution: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    extra_tax_data: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    debit: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    credit: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    balance: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_currency: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    tax_base_amount: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_residual: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_residual_currency: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    quantity: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    price_unit: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    price_subtotal: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    price_total: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    discount: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    discount_amount_currency: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    discount_balance: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    is_storno: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    is_imported: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    reconciled: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    is_downpayment: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    no_followup: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    collapse_composition: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    collapse_prices: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    move: Mapped["AccountMove"] = relationship("AccountMove", back_populates="line_ids")
    def __repr__(self): return f"<AccountMoveLine(id={self.id}, move_id={self.move_id}, name={self.name})>"
