#!/bin/sh

set -e

MASHORA_CONFIGURATION_FILE=/etc/mashora/mashora.conf
MASHORA_GROUP="mashora"
MASHORA_DATA_DIR=/var/lib/mashora
MASHORA_LOG_DIR=/var/log/mashora
MASHORA_USER="mashora"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    configure)
        if ! getent passwd | grep -q "^mashora:"; then
            adduser --system --home $MASHORA_DATA_DIR --quiet --group $MASHORA_USER
            # Data dir
            chown $MASHORA_USER:$MASHORA_GROUP $MASHORA_DATA_DIR
        fi
        # Register "$MASHORA_USER" as a postgres user with "Create DB" role attribute
        su - postgres -c "createuser -d -R -S $MASHORA_USER" 2> /dev/null || true
        # Configuration file
        chown $MASHORA_USER:$MASHORA_GROUP $MASHORA_CONFIGURATION_FILE
        chmod 0640 $MASHORA_CONFIGURATION_FILE
        # Log
        mkdir -p $MASHORA_LOG_DIR
        chown $MASHORA_USER:$MASHORA_GROUP $MASHORA_LOG_DIR
        chmod 0750 $MASHORA_LOG_DIR
        	# work around https://bugs.debian.org/1059326

        if ! [ -e ${GSFONTS_DIR}/n021003l.pfb ] ; then
            if ! [ -d ${GSFONTS_DIR} ] ; then
                mkdir ${GSFONTS_DIR}
                touch ${GSFONTS_DIR}/.created-by-mashora-package
            fi
            ln -s /usr/share/fonts/X11/Type1/C059-Roman.pfb ${GSFONTS_DIR}/n021003l.pfb
        fi
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
