"""Sale Order and Order Line models."""
from datetime import date, datetime
from typing import Optional
from sqlalchemy import Boolean, Date, DateTime, Float, Integer, Numeric, String, Text, ForeignKey
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base, TimestampMixin

class SaleOrder(Base, TimestampMixin):
    __tablename__ = "sale_order"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    company_id: Mapped[int] = mapped_column(Integer, nullable=False)
    partner_id: Mapped[int] = mapped_column(Integer, nullable=False)
    partner_invoice_id: Mapped[int] = mapped_column(Integer, nullable=False)
    partner_shipping_id: Mapped[int] = mapped_column(Integer, nullable=False)
    fiscal_position_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    payment_term_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    pricelist_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    currency_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    user_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    team_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    journal_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    campaign_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    source_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    medium_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    opportunity_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    warehouse_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    pending_email_template_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    preferred_payment_method_line_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    incoterm: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    access_token: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    name: Mapped[str] = mapped_column(String, nullable=False)
    state: Mapped[Optional[str]] = mapped_column(String, nullable=True, server_default="draft")
    client_order_ref: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    origin: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    reference: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    signed_by: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    invoice_status: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    picking_policy: Mapped[str] = mapped_column(String, nullable=False)
    delivery_status: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    incoterm_location: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    validity_date: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    note: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    currency_rate: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_untaxed: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_tax: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    amount_total: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    prepayment_percent: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    locked: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    require_signature: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    require_payment: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    date_order: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    commitment_date: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    signed_on: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    effective_date: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    order_line: Mapped[list["SaleOrderLine"]] = relationship("SaleOrderLine", back_populates="order", lazy="selectin")
    def __repr__(self): return f"<SaleOrder(id={self.id}, name={self.name}, state={self.state})>"

class SaleOrderLine(Base, TimestampMixin):
    __tablename__ = "sale_order_line"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    order_id: Mapped[int] = mapped_column(Integer, ForeignKey("sale_order.id"), nullable=False)
    sequence: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    company_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    currency_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    order_partner_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    salesman_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    product_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    product_uom_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    linked_line_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    combo_item_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    warehouse_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    state: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    display_type: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    qty_delivered_method: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    invoice_status: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    analytic_distribution: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    extra_tax_data: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    product_uom_qty: Mapped[float] = mapped_column(Numeric, nullable=False)
    price_unit: Mapped[float] = mapped_column(Numeric, nullable=False)
    discount: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    price_subtotal: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    price_total: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    price_reduce_taxexcl: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    price_reduce_taxinc: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    qty_delivered: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    qty_invoiced: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    qty_to_invoice: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    untaxed_amount_invoiced: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    untaxed_amount_to_invoice: Mapped[Optional[float]] = mapped_column(Numeric, nullable=True)
    price_tax: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    technical_price_unit: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    customer_lead: Mapped[float] = mapped_column(Float, nullable=False)
    is_downpayment: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    is_expense: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    collapse_prices: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    collapse_composition: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    order: Mapped["SaleOrder"] = relationship("SaleOrder", back_populates="order_line")
    def __repr__(self): return f"<SaleOrderLine(id={self.id}, order_id={self.order_id}, product_id={self.product_id})>"
